config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment_content
    %p.comment_name= comment.name
    %p.comment_body= comment.body
    %p.comment_title= time_ago_in_words(@post.created_at)
  - if user_signed_in?
    %p= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
= simple_form_for [@post, @post.comments.build] do |f|
  = f.label :name
  %br
  = f.text_field :name
  %br
  = f.label :body
  %br
  = f.text_area :body
  %br
  = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- favicon for logo img -->
    <%= favicon_link_tag 'micro.png' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id='sidebar'>
      <ul>
        <li class="category"><%= link_to "Microblog", root_path %></li>
        <li><%= link_to 'Posts', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      <% if !user_signed_in? %>
        <p class="sign_up"><%= link_to 'Sign Up', new_user_registration_path %></p>
        <p class="sign_in"><%= link_to 'User Login', new_user_session_path %></p>
      <% end %>
    </div>

    <div id='main_content'>
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% else current_page?(root_path) %>
          <p>About</p>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="buttons">
          <%= link_to "<button class='button' type='button'>Make Post</button>".html_safe, new_post_path %>
          <%= link_to "<button class='button' type='button'>Log Out</button>".html_safe, destroy_user_session_path, method: :delete %>
        </div>
      <% end %>

      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: 'alert') %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.haml
#page_wrapper
  #profile_image
    = image_tag 'sticks.png'
  #content
    %h1 Hello it's us
    %p Vegan +1 banjo, artisan migas mustache venmo affogato whatever yr synth. Messenger bag four dollar toast viral biodiesel. Narwhal photo booth man braid, crucifix knausgaard kitsch chicharrones master cleanse migas. Twee microdosing typewriter fap echo park, yuccie poutine +1 schlitz. Franzen roof party man braid fixie meditation. Kickstarter vinyl ramps, celiac 90's pickled meh messenger bag selvage retro. Ramps viral kitsch banh mi, taxidermy fap single-origin coffee roof party williamsburg shabby chic chambray vice pabst.

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  - if @post.errors.any?
    #errors
      %h2
      = pluralize(@post.errors.count, 'error')
      prevented this comic from saving
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  =f.label :title
  =f.text_field :title
  %br
  =f.label :body
  =f.text_area :body
  %br
  =f.submit

app/views/posts/edit.html.haml
#page_wrapper
  %h1 Edit Post

  = render 'form'

  %button.cancel= link_to 'Cancel', post_path

app/views/posts/index.html.haml
- @posts.each do |post|
  %a{ href: (url_for [post])}
    %div.post_wrapper
      %h2.title= post.title
      %p.body= truncate(post.body, length:100)
      %p.date= time_ago_in_words(post.created_at)

app/views/posts/new.html.haml
#page_wrapper
  %h1 Create new post

  = render 'form'

  %button.cancel= link_to 'Cancel', root_path

app/views/posts/show.html.haml
#post_content
  %h1.title= @post.title
  %p.date= time_ago_in_words(@post.created_at)
  %p.body= @post.body
  - if user_signed_in?
    #buttons
      = link_to 'Edit', edit_post_path, class: 'button'
      = link_to 'Delete', post_path, class: 'button', method: :delete, data: { confirm: 'Are you sure?' }
      = link_to "All Posts", root_path, class: 'button'
  #comments
    %h2= @post.comments.count
    = render @post.comments
    %h3 Joing Discussion:
    = render 'comments/form'